# Generated by Django 3.1.2 on 2021-04-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('country', models.TextField(blank=True, max_length=30)),
                ('city', models.TextField(blank=True, max_length=30)),
                ('street', models.TextField(blank=True, max_length=30)),
                ('house_number', models.IntegerField(blank=True)),
                ('apartment_number', models.IntegerField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('main_language', models.CharField(blank=True, max_length=25)),
                ('other_language', models.CharField(blank=True, max_length=20)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_country', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_region', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_city', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_place', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_restaurant', models.TextField(blank=True, max_length=30, null=True)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
