# Generated by Django 3.0.4 on 2020-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apartment_number',
            field=models.IntegerField(blank=True, default=1345, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='main_language',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
