# Generated by Django 3.0.4 on 2020-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200828_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apartment_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(blank=True),
        ),
    ]
