# Generated by Django 3.0.4 on 2020-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200828_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_country', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_region', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_city', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_place', models.TextField(blank=True, max_length=30, null=True)),
                ('favorite_restaurant', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
