# Generated by Django 3.0.4 on 2020-09-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200905_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
            preserve_default=False,
        ),
    ]
