# Generated by Django 3.1.2 on 2021-04-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210424_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apartment_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
