# Generated by Django 3.1.2 on 2021-04-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210428_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('', ''), ('USER_VIP', 'USER_VIP'), ('MODERATOR', 'MODERATOR'), ('ADMIN', 'ADMIN')], default='', max_length=30),
        ),
    ]
