# Generated by Django 3.1.2 on 2021-04-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210428_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
