# Generated by Django 3.1.2 on 2021-02-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coordinateX', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
                ('coordinateY', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('coordinateX', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
                ('coordinateY', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
                ('image', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('type', models.CharField(choices=[('Zamki', 'Zamki'), ('Forty', 'Forty'), ('Kościoły', 'Kościoły'), ('Muzeum', 'Muzeum'), ('Parki', 'Parki'), ('Ogrody', 'Ogrody'), ('Pomniki', 'Pomniki'), ('Rynki', 'Rynki'), ('Mosty', 'Mosty'), ('Wieże', 'Wieże'), ('Stadiony', 'Stadiony'), ('Cmentarze', 'Cmentarze'), ('Budowle', 'Budowle'), ('Porty', 'Porty'), ('Filcharmonie', 'Filcharmonie')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion_about_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('opinion', models.CharField(max_length=530)),
                ('rating', models.IntegerField()),
                ('point', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='map.point')),
            ],
        ),
    ]
