# Generated by Django 3.0.5 on 2020-05-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
