# Generated by Django 3.0.5 on 2020-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0002_delete_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coordinateX', models.CharField(max_length=30)),
                ('coordinateY', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('descriptions', models.TextField()),
                ('type', models.CharField(choices=[('castle', 'Zamek'), ('church', 'Kościół')], max_length=10)),
            ],
        ),
    ]
