# Generated by Django 3.1.2 on 2021-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_newsletteremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='country',
            field=models.CharField(choices=[('Polska', 'Polska'), ('Niemcy', 'Niemcy'), ('Czechy', 'Czechy'), ('Słowacja', 'Słowacja'), ('Rosja', 'Rosja'), ('Ukraina', 'Ukraina'), ('Białoruś', 'Białoruś'), ('Litwa', 'Litwa'), ('Estonia', 'Estonia'), ('Włochy', 'Włochy'), ('Izrael', 'Izrael')], default='Polska', max_length=15),
        ),
    ]
