# Generated by Django 3.0.5 on 2020-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
        ('map', '0003_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='trails',
            field=models.ManyToManyField(to='trails.Trails'),
        ),
    ]
