# Generated by Django 3.1.2 on 2021-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_point_addresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='addresse',
            new_name='address',
        ),
        migrations.AddField(
            model_name='point',
            name='more_info',
            field=models.CharField(default=' ', max_length=70),
        ),
        migrations.AddField(
            model_name='point',
            name='region',
            field=models.CharField(choices=[('Góry', 'Góry'), ('Pojezierze', 'Pojezierze'), ('Morze', 'Morze'), ('Nizinny', 'Nizinny')], default='Nizinny', max_length=15),
        ),
    ]
