# Generated by Django 3.1.2 on 2021-04-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210429_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image1', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('image2', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('image3', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('image4', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
                ('image5', models.ImageField(upload_to='media/img_point/%Y/%m%d')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='publications',
            field=models.ManyToManyField(to='map.Galery'),
        ),
    ]
