# Generated by Django 3.1.2 on 2021-04-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210430_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='publications',
            new_name='gallery',
        ),
    ]
