# Generated by Django 3.0.5 on 2020-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_remove_trail_points'),
        ('map', '0007_remove_point_trails'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='trails',
            field=models.ManyToManyField(blank=True, null=True, to='trails.Trail'),
        ),
    ]
