# Generated by Django 3.1.2 on 2021-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20210430_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image1',
            field=models.ImageField(blank=True, upload_to='media/img_point/%Y/%m%d'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/img_point/%Y/%m%d'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image3',
            field=models.ImageField(blank=True, upload_to='media/img_point/%Y/%m%d'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image4',
            field=models.ImageField(blank=True, upload_to='media/img_point/%Y/%m%d'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image5',
            field=models.ImageField(blank=True, upload_to='media/img_point/%Y/%m%d'),
        ),
    ]
