# Generated by Django 3.0.5 on 2020-05-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_remove_trail_points'),
        ('map', '0008_point_trails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='trails',
        ),
        migrations.AddField(
            model_name='point',
            name='trails',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='trails.Trail'),
            preserve_default=False,
        ),
    ]
