# Generated by Django 3.1.2 on 2021-05-07 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='downloads_point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='heart',
            field=models.ManyToManyField(blank=True, related_name='heart_point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='sound',
            field=models.ManyToManyField(blank=True, related_name='sound_point', to=settings.AUTH_USER_MODEL),
        ),
    ]
