# Generated by Django 3.0.5 on 2020-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_remove_trail_points'),
        ('map', '0009_auto_20200515_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='trails',
        ),
        migrations.AddField(
            model_name='point',
            name='trails',
            field=models.ManyToManyField(blank=True, to='trails.Trail'),
        ),
    ]
