# Generated by Django 3.1.2 on 2021-05-11 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0010_auto_20210507_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('Zamki', 'Zamki'), ('Forty', 'Forty'), ('Kościoły', 'Kościoły'), ('Muzeua', 'Muzeua'), ('Parki', 'Parki'), ('Hotele', 'Hotele'), ('Ogrody', 'Ogrody'), ('Pomniki', 'Pomniki'), ('Rynki', 'Rynki'), ('Mosty', 'Mosty'), ('Wieże', 'Wieże'), ('Stadiony', 'Stadiony'), ('Cmentarze', 'Cmentarze'), ('Budowle', 'Budowle'), ('Porty', 'Porty'), ('Filcharmonie', 'Filcharmonie')], max_length=15),
        ),
        migrations.CreateModel(
            name='Hearts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
