# Generated by Django 3.1.2 on 2021-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20210507_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='average_grade',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('Zamki', 'Zamki'), ('Forty', 'Forty'), ('Kościoły', 'Kościoły'), ('Muzeua', 'Muzeua'), ('Parki', 'Parki'), ('Hotele', 'Hotele'), ('Ogrody', 'Ogrody'), ('Pomniki', 'Pomniki'), ('Rynki', 'Rynki'), ('Mosty', 'Mosty'), ('Wieże', 'Wieże'), ('Stadiony', 'Stadiony'), ('Cmentarze', 'Cmentarze'), ('Budowle', 'Budowle'), ('Porty', 'Porty'), ('Filcharmonie', 'Filcharmonie')], max_length=15),
        ),
    ]
