# Generated by Django 3.1.2 on 2021-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20210511_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hearts',
        ),
    ]
