# Generated by Django 3.1.2 on 2021-05-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20210513_1237'),
        ('map', '0012_delete_hearts'),
    ]

    operations = [
    ]
