# Generated by Django 3.1.2 on 2021-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_merge_20210514_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
    ]
