# Generated by Django 3.1.2 on 2021-05-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_point_done_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/advertisement')),
                ('url', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
