# Generated by Django 3.0.4 on 2020-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20200723_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='location',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('Zamek', 'Zamek'), ('Kościół', 'Kościół')], max_length=10),
        ),
    ]
