# Generated by Django 3.1.2 on 2021-05-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_advertisementnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coordinateX', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
                ('coordinateY', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
            ],
        ),
    ]
