# Generated by Django 3.0.4 on 2020-08-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20200803_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion_about_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=5, max_digits=5, max_length=10)),
                ('amount_rating', models.DecimalField(decimal_places=5, max_digits=5, max_length=10)),
                ('point', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='map.Point')),
            ],
        ),
    ]
