# Generated by Django 3.1.2 on 2021-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_point_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='sound',
        ),
        migrations.AddField(
            model_name='point',
            name='sound',
            field=models.FileField(blank=True, upload_to='media/musics/points'),
        ),
    ]
