# Generated by Django 3.1.2 on 2021-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20210603_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='for_whom',
            field=models.CharField(choices=[('Dla wszystkich', 'Dla wszystkich'), ('Dla dzieci', 'Dla dzieci'), ('Dla dorosłych', 'Dla dorosłych'), ('Dla sportowców', 'Dla sportowców'), ('Dla wymagających', 'Dla wymagających')], default='Dla wszystkich', max_length=25),
        ),
    ]
