# Generated by Django 3.0.4 on 2020-08-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20200816_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion_about_point',
            name='amount_rating',
        ),
    ]
