# Generated by Django 3.0.4 on 2020-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_remove_opinion_about_point_amount_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion_about_point',
            name='opinion',
            field=models.CharField(default='Przykladowa opinia', max_length=530),
            preserve_default=False,
        ),
    ]
