# Generated by Django 3.0.4 on 2020-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_opinion_about_point_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion_about_point',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
