# Generated by Django 3.1.2 on 2020-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='user',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
