# Generated by Django 3.0.5 on 2020-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
