# Generated by Django 3.0.4 on 2020-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
