# Generated by Django 3.1.2 on 2021-05-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_photo_first',
            field=models.ImageField(blank=True, upload_to='media/img/%Y/%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='additional_photo_second',
            field=models.ImageField(blank=True, upload_to='media/img/%Y/%m%d'),
        ),
    ]
