# Generated by Django 3.1.2 on 2021-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='country',
            field=models.CharField(choices=[('Polska', 'Polska'), ('Niemcy', 'Niemcy'), ('Czechy', 'Czechy'), ('Słowacja', 'Słowacja'), ('Rosja', 'Rosja'), ('Ukraina', 'Ukraina'), ('Białoruś', 'Białoruś'), ('Litwa', 'Litwa'), ('Estonia', 'Estonia'), ('Włochy', 'Włochy'), ('Izrael', 'Izrael')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.CharField(choices=[('Góry', 'Góry'), ('Pojezierze', 'Pojezierze'), ('Morze', 'Morze'), ('Nizinny', 'Nizinny')], default='Nizinny', max_length=15),
        ),
    ]
