# Generated by Django 3.1.2 on 2021-02-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='points',
        ),
    ]
