# Generated by Django 3.0.5 on 2020-05-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_point_trails'),
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trails',
            new_name='Trail',
        ),
    ]
