# Generated by Django 3.0.5 on 2020-05-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_trails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='trails',
            new_name='points',
        ),
    ]
