# Generated by Django 3.1.2 on 2021-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_auto_20210503_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='for_whom',
            field=models.CharField(choices=[('Dla wszystkich', 'Dla wszystkich'), ('Dla dzieci', 'Dla dzieci'), ('Dla dorosłych', 'Dla dorosłych'), ('Dla sportowców', 'Dla sportowców'), ('Dla wymagających', 'Dla wymagających')], default='Dla wszystkich', max_length=25),
        ),
    ]
