# Generated by Django 3.0.5 on 2020-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_point_trails'),
        ('trails', '0005_remove_trail_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='points',
            field=models.ManyToManyField(to='map.Point'),
        ),
    ]
