# Generated by Django 3.0.3 on 2020-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_remove_trail_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/img_trail/%Y/%m%d'),
        ),
    ]
