# Generated by Django 3.1.2 on 2021-02-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_auto_20210208_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='points',
        ),
    ]
