# Generated by Django 3.1.2 on 2021-05-07 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0008_auto_20210507_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='sound',
            field=models.ManyToManyField(blank=True, related_name='sound', to=settings.AUTH_USER_MODEL),
        ),
    ]
