# Generated by Django 3.1.2 on 2020-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='average_grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
