# Generated by Django 3.1.2 on 2021-05-07 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0009_trail_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_trail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trail',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='downloads_trail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trail',
            name='heart',
            field=models.ManyToManyField(blank=True, related_name='heart_trail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trail',
            name='sound',
            field=models.ManyToManyField(blank=True, related_name='sound_trail', to=settings.AUTH_USER_MODEL),
        ),
    ]
