# Generated by Django 3.1.2 on 2020-11-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0009_auto_20201124_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rate_trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('opinion', models.TextField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
