# Generated by Django 3.1.2 on 2020-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_auto_20201127_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='watched',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
