# Generated by Django 3.1.2 on 2021-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_auto_20210507_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
    ]
