# Generated by Django 3.1.2 on 2020-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_trail_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='region',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='type',
            field=models.CharField(choices=[('Krajoznawcza', 'krajoznawcza'), ('Rodzinna', 'Rodzinna'), ('Górska', 'Górska'), ('Wymagająca', 'Wymagająca'), ('Wakacyjna', 'Wakacyjna'), ('Inna', 'Inna')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
