# Generated by Django 3.1.2 on 2020-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_auto_20201207_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='country',
            field=models.CharField(choices=[('Polska', 'Polska'), ('Niemcy', 'Niemcy')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
