# Generated by Django 3.1.2 on 2021-06-05 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0012_remove_trail_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='auditions',
            field=models.ManyToManyField(blank=True, related_name='auditions_trail', to=settings.AUTH_USER_MODEL),
        ),
    ]
