# Generated by Django 3.1.2 on 2020-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0013_trail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='country',
            field=models.CharField(choices=[('Polska', 'Polska'), ('Niemcy', 'Niemcy')], default='Polska', max_length=15),
        ),
    ]
