# Generated by Django 3.1.2 on 2021-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_auto_20210606_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='downloads',
        ),
        migrations.AddField(
            model_name='trail',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
