# Generated by Django 3.1.2 on 2020-12-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_auto_20201207_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='country',
            field=models.CharField(choices=[('Polska', 'Polska'), ('Niemcy', 'Niemcy')], max_length=15),
        ),
    ]
