# Generated by Django 3.1.2 on 2020-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0015_auto_20201207_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
