# Generated by Django 3.0.4 on 2020-08-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media/img_trail/%Y/%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('coordinateX', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
                ('coordinateY', models.DecimalField(decimal_places=7, max_digits=100, max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=15)),
                ('trails', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_trails.UserTrail')),
            ],
        ),
    ]
