# Generated by Django 3.0.4 on 2020-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrail',
            name='image',
            field=models.ImageField(upload_to='media/img_trail/%Y/%m%d'),
        ),
    ]
