# Generated by Django 3.1.2 on 2021-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0002_auto_20210501_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrail',
            name='country',
            field=models.CharField(choices=[('Polska', 'Polska'), ('Niemcy', 'Niemcy'), ('Czechy', 'Czechy'), ('Słowacja', 'Słowacja'), ('Rosja', 'Rosja'), ('Ukraina', 'Ukraina'), ('Białoruś', 'Białoruś'), ('Litwa', 'Litwa'), ('Estonia', 'Estonia'), ('Włochy', 'Włochy'), ('Izrael', 'Izrael'), ('Różne', 'Różne')], default='Polska', max_length=15),
        ),
    ]
