# Generated by Django 3.0.4 on 2020-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0003_remove_usertrail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrail',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
