# Generated by Django 3.1.2 on 2021-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0003_auto_20210502_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrail',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/static/img/'),
        ),
    ]
