# Generated by Django 3.0.4 on 2020-08-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0005_auto_20200810_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrail',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
