# Generated by Django 3.0.4 on 2020-08-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0006_auto_20200810_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrail',
            name='user',
        ),
    ]
