# Generated by Django 3.1.2 on 2021-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0009_auto_20210502_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrail',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/img_trail/%Y/%m%d'),
        ),
    ]
