# Generated by Django 3.1.2 on 2021-06-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trails', '0011_auto_20210518_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrail',
            name='auditions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertrail',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
