# Generated by Django 3.1.2 on 2020-10-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='author',
        ),
    ]
