# Generated by Django 3.1.2 on 2020-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_message_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
