# Generated by Django 3.1.2 on 2020-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201114_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payments',
            field=models.BooleanField(default=False),
        ),
    ]
