# Generated by Django 3.0.5 on 2020-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paind',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
